// **********************************************************************
// Parsed By TarsParser(1.1.0), Generated By tars2node(20190109)
// TarsParser Maintained By <TARS> and tars2node Maintained By <superzheng>
// Generated from "NodeJsComm.tars" by Imp Mode
// **********************************************************************

"use strict";

var TRom = require("./NodeJsComm.js").TRom;
module.exports.TRom = TRom;

TRom.NodeJsCommImp.prototype.initialize = function () {
    //TODO::
};

TRom.NodeJsCommImp.prototype.test = function (current) {
    //TODO::
};

TRom.NodeJsCommImp.prototype.getall = function (current, stUser, stResult) {
    //TODO::
};

TRom.NodeJsCommImp.prototype.getUsrName = function (current, sUsrName, sValue1, sValue2) {
    //TODO::
};

TRom.NodeJsCommImp.prototype.secRequest = function (current, binRequest, binResponse) {
    //TODO::
};


